query LatestEpisodes {
  allEpisode(sort: [{ date: DESC }], limit: 4) {
    _id
    episode
    date
    runtime
    title
    description
    youtubeUrl
    twitchUrl
    facebookUrl
    linkedinUrl
  }
}
