import { Nav } from "@/components/nav";
import "./globals.css";
import { Inter, Roboto, Aboreto } from "next/font/google";
import classNames from "classnames";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="acid">
      <body className={classNames(roboto.className)}>
        <Nav />
        <div className="flex flex-col items-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
